### ISSUE TITLE
🐛 [BUG] TorchScript error

### ISSUE THREAD

**Issue by schiotz** [mir-group/nequip#121]
**Describe the bug**
I am trying to reproduce the MRS2021 tutorial, but with the ASE interface.  It worked in the colab notebook, but I get a TorchScript error when I try to install on our cluster here at DTU Physics.  Nequip is installed into a venv from the developer branch with ``pip -e nequip/``.  PyTorch is installed on the cluster using EasyBuild, it is version 1.9.0 built with the foss/2020b toolchain.  The pip-installed version does not support our GPUs.

**To Reproduce**
The model was trained with the following script
```source ../venv/bin/activate

rm -rf ./results
nequip-train ../nequip/configs/example.yaml
nequip-deploy build results/toluene/example-run-toluene toluene-deployed.pth
nequip-evaluate --train-dir results/toluene/example-run-toluene --batch-size 50
```

The attached script was then run, it produced the attach error message. 

**Expected behavior**
No crash :-)

**Environment (please complete the following information):**
 - OS: CentOS 7.9, but all software built with EasyBuild (foss/2020b toolchain)
 - python version 3.8.6
 - python environment (commands are given for python interpreter):
   - nequip version 0.5.0
   - e3nn version 0.4.3
   - pytorch version 1.9.0
 - (if relevant) GPU support with CUDA
   -  cuda Version according to nvcc Cuda compilation tools, release 11.1, V11.1.105   Build cuda_11.1.TC455_06.29190527_0
   -  cuda version according to PyTorch 11.1

**Additional context**
Add any other context about the problem here
[slurm-4259922.log](https://github.com/mir-group/nequip/files/7659357/slurm-4259922.log)
.
[runoptimize.py.txt](https://github.com/mir-group/nequip/files/7659363/runoptimize.py.txt)

**Comment by schiotz** [comment]
Follow-up:  I updated to PyTorch 1.9.1, same error.

**Comment by schiotz** [comment]
Follow-up 3:

This is neither related to our GPUs, nor to having PyTorch installed with EasyBuild.

I tried it out on another cluster with NVIDIA TITAN Xp gpus, and with python and pytorch installed with ``conda``.  Same result.

**Comment by schiotz** [comment]
**PROBLEM SOLVED:**

I think it is a documentation problem.  According to the main page (README.md), "NequIP is also not currently compatible with PyTorch 1.10; PyTorch 1.9 can be specified with pytorch==1.9 in the install command."  

It looks like PyTorch 1.9 is the problem, upgrading to 1.10.0 is solving the issue.

**Comment by Linux-cpp-lisp** [comment]
Hi @schiotz —

Wow! You were busy working on a solution before I even got a chance to respond, really appreciate it!

This is something we've seen before and it's the result of a [PyTorch bug](https://github.com/pytorch/pytorch/issues/63923) (one that frankly I'm amazed didn't get surfaced and fixed sooner). The bug is fixed in 1.10.

Unfortunately, the version stuff in the README is not actually entirely a typo... this bug does not happen consistently and _so far_ from my testing PyTorch 1.10 seems to introduce entirely new difficult to debug/reproduce TorchScript bugs. That was my reasoning so far for keep the allowed version down.

For the moment, given that we seem to have success on some systems with 1.9 and mysterious failure on others with 1.10, I'm gonna keep 1.9 as the current max on main and point those like you who have this issue to install 1.10. In the meantime I will try to get our develop branch fully working on 1.10 so we can leave this confusion behind.

Please let me know if 1.10 is/is not working for you! That will help me understand what exactly is going on.

Thanks!

**Comment by schiotz** [comment]
Thanks for your comments, it makes a lot of sense.  

Depending on large third-party packages saves a lot of work, but occasionally gives a bit of trouble when bugs and incompatibilites are introduces - we run into the same kind of issues with ASE, so I fully understand the situation. :-)

**Comment by simonbatzner** [comment]
Closing this, thanks @schiotz!
