### ISSUE TITLE
❓ [QUESTION] Dataset preprocessing computation times

### ISSUE THREAD

**Issue by pdobbelaere** [mir-group/nequip#122]
Hi, 

I'm experiencing some weird behaviour with the dataset preprocessing step. Depending on specific combinations of lattice vectors and pbcs, this preprocessing can take an unexpected amount of time. To frame the following, I'm extracting clusters of atoms from periodic UiO-66. 

Three different (very small) datasets in the added zip-file nicely illustrate this:
- 'clusters_a.xyz' contains 10 clusters extracted from a 2x2x2 supercell. These still have the lattice vectors from the periodic system and enabled pbcs. The cell is much larger than a reasonable interaction radius, so there are no artificial periodic interactions.
- 'clusters_b.xyz' contains the same set of clusters, with the original periodic lattice vectors and disabled pbcs.
- 'clusters_c.xyz' once again contains the same clusters, this time without lattice vectors altogether.

A very rough timing job revealed that the first and third dataset preprocess in a comparable timespan (about half a second on my machine), whereas the second dataset took almost 2 orders of magnitude longer.

Any ideas as to where this discrepancy originates from? It can be easily avoided by a small change to the dataset, however, seems like it should not occur in the first place.

FYI, I recently updated to v0.5.0, but initially encountered this issue in v0.3.3.

[datasets.zip](https://github.com/mir-group/nequip/files/7660305/datasets.zip)

**Comment by simonbatzner** [comment]
Hi @pdobbelaere, I loaded your structures and ran the ASE neighborlist calculation that we use internally. I can confirm that I see the same behavior: 

A: PBC + cell are set, the neighborlist is aware of periodic images but since the cell is large never sees them, all is fine
B: PBC is false, cell is set, much slower. 
C: PBC is false, cell is not there, this is equivalent to A since the cutoff is small enough in A that it's the same as if it was just in vacuum

[This](https://wiki.fysik.dtu.dk/ase/_modules/ase/neighborlist.html#primitive_neighbor_list ) is the neighborlist we use. Note that the docs say: 

> Atoms outside periodic boundaries are mapped into the box. Atoms
    outside nonperiodic boundaries are included in the neighbor list
    but complexity of neighbor list search for those can become n^2.

Looking at your structure your atoms lie right on the border, hence you're seeing the N^2 scaling of ASE. When I shift them to the middle of the cell, the behavior goes away. 

```
import time
import numpy as np

from ase.io import read
from ase.neighborlist import neighbor_list

b = read('./clusters_b.xyz')

s = time.time()
ib, jb = neighbor_list('ij', b, cutoff=5., self_interaction=False)
e = time.time()
print(e-s)

# simple cubic cell
cell = b.get_cell()
center = cell[0][0]/ 2.

# shift to middle of box
p = b.get_positions()
p += np.array([center, center, center])
b.set_positions(p)
b.wrap()

s = time.time()
ib, jb = neighbor_list('ij', b, cutoff=5., self_interaction=False)
e = time.time()
print(e-s)
```
Gives: 

```
9.93855881690979
0.07891488075256348
```

**Comment by pdobbelaere** [comment]
Thanks very much for the speedy reply. That is good to know.
