### ISSUE TITLE
🌟 [FEATURE] `utils.config` as dataclass?

### ISSUE THREAD

**Issue by PythonFZ** [mir-group/nequip#192]
**Is your feature request related to a problem? Please describe.**
Whilst using nequip myself I was going through the code to better understand the parameter handling.
I'm not using `wandb` but [DVC](https://dvc.org/) with [ZnTrack](https://github.com/zincware/ZnTrack) and therefore, I'm currently using two nested subprocess calls (The first is DVC, the second is in ZnTrack). I was looking for a way to train the model directly (calling `train.main` basically).

Whilst looking for that I was wondering if the `Config` object
https://github.com/mir-group/nequip/blob/eb6f9bca7b36162abf69ebb017049599b4ddb09c/nequip/utils/config.py#L45

could be replaced by a Python dataclass?
I could see multiple benefits here:
- The default values could be stored in the dataclass instead of https://github.com/mir-group/nequip/blob/eb6f9bca7b36162abf69ebb017049599b4ddb09c/nequip/scripts/train.py#L26-L47
- The attributes could have docstrings that would help building the documentation. I like the way the `config.yaml` files are documented and that helped me a lot, but I think having a documented dataclass in addition could also be helpful.
- autocompletion of attributes

**Describe the solution you'd like**
I could have a look at it if there is some general interest.

**Additional context**

One could use the `__doc__` of the dataclass to automatically generate the `yaml` file including the documentation to only maintain it in one place. This would be a proof-of-concept example:

```py
import dataclasses
import yaml
import re


@dataclasses.dataclass
class Config:
    """
    Attributes:
        seed: model seed
        dataset_seed: data set seed
    """

    seed: int = 123456
    dataset_seed: int = 31415

    @property
    def to_yaml(self) -> str:
        """Convert the dataclass to a yaml string including documentation"""
        doc_dict = {}
        data_dict = {}

        for field in dataclasses.fields(self):
            data_dict[field.name] = getattr(self, field.name)
            doc_dict[field.name] = re.search( # not the final version
                rf"(?<={field.name}:).*", self.__doc__
            ).group(0)

        yaml_string = ""
        for line in yaml.dump(data_dict, indent=4).splitlines():
            for key in doc_dict:
                if line.startswith(key):
                    yaml_string += f"{line}    # {doc_dict[key]} \n"
                    break
            else:
                yaml_string += f"{line}\n"

        return yaml_string
```

**Comment by Linux-cpp-lisp** [comment]
> I was looking for a way to train the model directly (calling train.main basically).

This is definitely doable, but make sure as you said to call `train.main` and not try to call `Trainer` itself.
Also, unless it really messes with your workflow, I would encourage you to just spawn `nequip-train` processes using `subprocess` and `tempfile` rather than calling direct into the Python API. While I can't think of anything in particular that would break, `nequip-train` is really intended as the one and only public-facing API for the training process.  It plays around with some global state out of necessity to configure PyTorch, and I have no idea how that would work end up working if you did many different trainings in one process while changing things like `dtype`... similarly I would recommend avoiding multiple nequip training sessions in multiprocessing unless you spawn off `nequip-train` commands— PyTorch is pretty fragile under `multiprocessing` and trying to reinitialize OpenMP and CUDA.

> could be replaced by a Python dataclass?

`Config` is really much more of a glorified `dict` than `NamedTuple`— there is no fixed set of valid keys, and the defaults come from all over the code. If you keep reading through the source you'll see fairly heavy use of the call `instantiate`: we made the choice early on to prioritize flexibility and and to keep the definitions of parameters close to where they are used. This has the advantage of making it really easy to add new modules, etc. to the configuration system, but also means that there is no fixed list of valid options.

> The attributes could have docstrings that would help building the documentation. I like the way the config.yaml files are documented and that helped me a lot, but I think having a documented dataclass in addition could also be helpful.

An unfortunate downside of that choice, of which we are very aware, is that it makes auto-generating (and thus having) comprehensive docs quite complicated. The same option can — intentionally — be requested in many different places, and also overridden for some of them. Which class should the documentation come from? (etc.)  A prototypical example is the cutoff `r_max`: many different parts of the model need this information and all take it from the same parameter, but they also all do different things with it. I'm sure there is a way to solve this without too much effort, but so far we haven't thought of anything better than the annotated `example.yaml`.

**Comment by PythonFZ** [comment]
>  `nequip-train` is really intended as the one and only public-facing API for the training process

To not run into issues if there are some changes I will also stick to that.

> `Config` is really much more of a glorified `dict` than `NamedTuple`

I saw that it represents the `wandb.config` object which is used in a very similar way.
I guess I just missunderstood the usage of it.
