### ISSUE TITLE
🌟 [FEATURE] Add conda installation support

### ISSUE THREAD

**Issue by wuziqi-cmu** [mir-group/nequip#196]
**Is your feature request related to a problem? Please describe.**
The only way right now seems to be to download the repo and install nequip local using pip. However, mixing conda and pip in a conda virtual environment risks messing up packages installed by those two package managers.

**Describe the solution you'd like**
It would be awesome if you guys can add support for conda installation.

**Describe alternatives you've considered**
Alternatively, hosting on pypi also resolves the issue since I can simply use the conda skeleton command to build and install using conda.

**Additional context**

**Comment by Linux-cpp-lisp** [comment]
@wuziqi-cmu thanks for your interest in our code!

Hosting on PyPI is definitely in our plans, making NequIP available by conda is however not something we are going to consider at this point. Because NequIP itself is a pure Python package, I don't see many advantages and it seems from what I've seen to be a significant investment of effort.  If you or anyone else as a user wants to volunteer to maintain those package definitions we are certainly open to that.

Are you experiencing issues with the mixture of `conda` and `pip`, or is this more an issue of best practices? We have never experienced issues installing NequIP in conda environments using `pip`.

**Comment by wuziqi-cmu** [comment]
@Linux-cpp-lisp Thanks for the quick reply!

Yes, there's no issue yet, and more of an issue of best practices for me. It would be nice if you guys can host it on PyPI!

**Comment by Linux-cpp-lisp** [comment]
@wuziqi-cmu I've released the latest NequIP version to PyPI; future versions should release to their automatically. (https://pypi.org/project/nequip/)

Could you test installing from `pip` and let me know if it works?
