### ISSUE TITLE
🌟 [FEATURE]How to Train and Validate on Separate Datasets

### ISSUE THREAD

**Issue by Guackkk** [mir-group/nequip#378]
Hello!

I'm currently working on training Nequip. Is it possible to train and validate the model on different datasets? Any insights and guidance on this matter would be greatly appreciated. Thank you!

**Comment by Linux-cpp-lisp** [comment]
Hi @Guackkk ,

Thanks for your interest in our code!

During training, see https://github.com/mir-group/nequip/blob/main/configs/full.yaml#L154-L157.

Otherwise, you can use `nequip-evaluate` to evaluate error metrics and predictions of a trained model on any test or evaluation dataset specified using our YAML syntax in a separate YAML file passed with the `--dataset-config` option.

**Comment by Guackkk** [comment]
Thanks for your quick and kind reply!
