### ISSUE TITLE
minimal extxyz

### ISSUE THREAD

**Issue by euhruska** [mir-group/nequip#410]
The minimal example for extxyz with exact .extxyz and .yaml files as described in docs/howto/dataset.rst fails in colab:

https://colab.research.google.com/drive/1GLdSM5FPOgZz3LAkkH1nIEujCf08F32z?usp=sharing

Error is ''RuntimeError: Failed to build object with prefix `dataset` using builder `ASEDataset`"

**Comment by tft225** [comment]
I have a similar issue when I try to run the minimal.yaml example and I get "RuntimeError Failed to build object with prefix dataset using builder NPZDataset."  Does your error also say it was caused by a permission denied error?  I've spending an entire workday trying to set up different environments to get this code working and I can't avoid it lol.

**Comment by cw-tan** [comment]
Hi @euhruska ,

Thank you for your interest in NequIP. I tried to patch up your colab to make it work, but it's too far away from a complete config file for `nequip-train` to work. I would advise using [minimal.yaml](https://github.com/mir-group/nequip/blob/main/configs/minimal.yaml) and the other example config files for learning how to set up config files, especially [full.yaml](https://github.com/mir-group/nequip/blob/main/configs/full.yaml).

@tft225 , `RuntimeError Failed to build object with prefix dataset using builder NPZDataset.` just means `nequip` error'ed out while trying to process the dataset - it could be for a whole lot of different reasons. This case and your case are likely unrelated.
